USE AlquilaoRD;
GO

-- 04. CONTROL DE RENDIMIENTO (ÍNDICES) 
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_USUARIOS_CORREO' AND object_id = OBJECT_ID('tablas.USUARIOS'))
    CREATE INDEX IX_USUARIOS_CORREO ON tablas.USUARIOS(correo);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PROPIEDADES_USUARIO' AND object_id = OBJECT_ID('tablas.PROPIEDADES'))
    CREATE INDEX IX_PROPIEDADES_USUARIO ON tablas.PROPIEDADES(id_usuario);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PROPIEDADES_CATEGORIA' AND object_id = OBJECT_ID('tablas.PROPIEDADES'))
    CREATE INDEX IX_PROPIEDADES_CATEGORIA ON tablas.PROPIEDADES(id_categoria);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PROPIEDADES_DISPONIBLE' AND object_id = OBJECT_ID('tablas.PROPIEDADES'))
    CREATE INDEX IX_PROPIEDADES_DISPONIBLE ON tablas.PROPIEDADES(disponible);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_FAVORITOS_USUARIO' AND object_id = OBJECT_ID('tablas.FAVORITOS'))
    CREATE INDEX IX_FAVORITOS_USUARIO ON tablas.FAVORITOS(id_usuario);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MENSAJES_EMISOR' AND object_id = OBJECT_ID('tablas.MENSAJES'))
    CREATE INDEX IX_MENSAJES_EMISOR ON tablas.MENSAJES(id_emisor);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_MENSAJES_RECEPTOR' AND object_id = OBJECT_ID('tablas.MENSAJES'))
    CREATE INDEX IX_MENSAJES_RECEPTOR ON tablas.MENSAJES(id_receptor);
GO